services:
  - type: web
    runtime: docker
    name: kopdes-staging
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    autoDeployTrigger: checksPass
    envVars:
      - key: APP_ENV
        value: staging
      - key: APP_ADDRESS
        value: :8080
      - key: DATABASE_DRIVER
        value: pgx
      - key: DATABASE_URL
        fromDatabase:
          name: kopdes-staging-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: COOKIE_SECURE
        value: "true"
      - key: SERVICE_NAME
        value: kopdes-staging
      - key: SERVICE_VERSION
        value: staging
      - key: METRICS_ENABLED
        value: "true"
      - key: TRACING_ENABLED
        sync: false
      - key: TRACING_EXPORTER
        value: otlp
      - key: TRACING_ENDPOINT
        sync: false
      - key: TRACING_INSECURE
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false

databases:
  - name: kopdes-staging-db
    plan: free
    region: singapore
    databaseName: kopdes_staging
    user: kopdes_staging
